export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const SET_IDS_FILTER_ARTICLE_LIST = 'SET_IDS_FILTER_ARTICLE_LIST'

export const SET_DATE_FILTER_ARTICLE_LIST = 'SET_DATE_FILTER_ARTICLE_LIST'